version: '3'
services:
  owncloud:
    image: owncloud:8.1
    expose:
      - '80'
    #ports:
    #  - '8082:80'
    environment:
      - TZ=Asia/Tokyo
    restart: always
    networks:
      - private_nw
networks:
  private_nw:
    external: true
